### ISSUE TITLE
help !!

### ISSUE THREAD

**Issue by ChenZesen** [AOSP-LAND/device_xiaomi_land#2]
build/core/base_rules.mk:391: warning: ignoring old commands for target `/home/czs/mk/out/target/product/land/system/lib/libstagefright_soft_flacdec.so'
[ 99% 1585/1586] glob vendor/qc...s/display/config/1.0/Android.b
ninja: error: '/home/czs/mk/out/target/product/land/obj_arm/SHARED_LIBRARIES/libsdm-disp-vndapis_intermediates/export_includes', needed by '/home/czs/mk/out/target/product/land/obj_arm/SHARED_LIBRARIES/lights.msm8937_intermediates/import_includes', missing and no known rule to make it
01:24:39 ninja failed with: exit status 1

#### failed to build some targets (01:40 (mm:ss)) ####

**Comment by Devil7DK** [comment]
Clone display hals... If already did, remove project paths. And btw this is not place to ask build errors.... Unless it's in our sources. Go here https://t.me/Android_builders_chat
